# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='active_no',
            field=models.CharField(db_index=True, max_length=256, null=True, verbose_name='Number'),
        ),
    ]
