# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170621_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='active_trucks',
            field=models.IntegerField(default=0),
        ),
    ]
